trigger:

- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: 'k8s.helm.test/k8s.helm.test.csproj'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'k8s.helm.test/k8s.helm.test.csproj'

- task: Docker@2
  inputs:
    containerRegistry: 'itdepends-acr-connection'
    repository: 'k8s.test.app'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'


# - task: OctopusCreateRelease@4
#   inputs:
#     OctoConnectedServiceName: 'ItDependsOctopusDeploy'
#     Space: 'Spaces-1'
#     ProjectName: 'Projects-1'
#     ReleaseNumber: '$(Build.BuildNumber)'
#     Channel: 'Channels-1'
#     DeployToEnvironment: 'Environments-21'
#     DeploymentProgress: true
# - task: OctopusDeployRelease@4
#   inputs:
#     OctoConnectedServiceName: 'ItDependsOctopusDeploy'
#     Space: 'Spaces-1'
#     Project: 'Projects-1'
#     ReleaseNumber: '$(Build.BuildNumber)'
#     Environments: 'Environments-21'