trigger:
- master
 
pool:
  vmImage: 'ubuntu-latest'
 
 
steps:
- task: HelmInstaller@1
  inputs:
    helmVersionToInstall: 'latest'
 
- script: |
    helm lint ./itdepends
    helm package ./itdepends
  displayName: 'Packaging helm'
- task: AzureCLI@2
  inputs:
    azureSubscription: 'HelmPublish'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az acr helm repo add --name itdepends
      package="$(find -name *.tgz)"
      az acr helm push --name itdepends $package
    failOnStandardError: true
